### PR TITLE
#253 death camera & spec mode mouse not working

### LINKED ISSUE #253: [BUG] Death Camera & Spec Mode mouse not working
**Describe the bug**
When the player dies or goes within specator mode, they can view other players and navigate across the map. The movement keys (WASD) are working, but the player cannot use their mouse to change the view direction. Additionally pressing right click freezes the movement keys as well, this is also unintended.

**To Reproduce**
1. Host any lobby (Singleplayer or Multiplayer)
2. Die or enter spec mode (/specmode)
3. The mouse cannot be used to look freely.

**Expected behavior**
It is expected that players can freely look around while they are dead, and that pressing right click will no longer freeze the camera.

### PR DESCRIPTION
**Pull request by FAStre**
Closes #253

### CODE REVIEW

**Comment by FAStre** [comment]
fixing sonar issues

**Review by Lithrun — COMMENTED** [review]
Code is good in terms of maintainability.
Will approve once build is accepted by the testing team

**Comment by FAStre** [comment]
fixing tester issues

**Comment by Lithrun** [comment]
No need to close a pull request for that. Just keep it open

**Comment by Lithrun** [comment]
The two `csharpsquid:S109` from Sonarcloud can be ignored as those will be marked as obsolete for #266 and a future cleanup issue.

File: Assets/Scripts/FengGameManagerMKII.cs [hunk 1]
```diff
@@ -464,10 +464,10 @@ private void core2()
         else
         {
             if (IN_GAME_MAIN_CAMERA.gametype == GAMETYPE.Stop) return;
-            if (this.needChooseSide)
-            {
-                InGameUI.SpawnMenu.gameObject.SetActive(true);
-            }
+             if (this.needChooseSide)
```
Comment (Lithrun) [inline Assets/Scripts/FengGameManagerMKII.cs:437]: Undo this change

File: Assets/Scripts/FengGameManagerMKII.cs [hunk 2]
```diff
@@ -502,10 +502,11 @@ private void core2()
                      (Camera.main.GetComponent<IN_GAME_MAIN_CAMERA>().gameOver && !this.needChooseSide)) &&
                     (((int) settings[0xf5]) == 0))
                 {
-                    this.ShowHUDInfoCenter(
-                        $"Press <color=#f7d358>{InputManager.GetKey(InputHuman.Item1)}</color> to spectate the next player.\n" +
-                        $"Press <color=#f7d358>{InputManager.GetKey(InputHuman.Item2)}</color> to spectate the previous player.\n" +
-                        $"Press <color=#f7d358>{InputManager.GetKey(InputHuman.AttackSpecial)}</color> to enter the spectator mode.\n\n\n\n");
+                    this.ShowHUDInfoCenter(     
+                $"Press <color=#f7d358>{InputManager.GetKey(InputHuman.Item1)}</color> to open the spawn menu.\n" +
```
Comment (Lithrun) [inline Assets/Scripts/FengGameManagerMKII.cs]: Replace "open" with "Toggle"

File: Assets/Scripts/FengGameManagerMKII.cs [hunk 3]
```diff
@@ -856,6 +857,14 @@ public void EnterSpecMode(bool enter)
             Camera.main.GetComponent<IN_GAME_MAIN_CAMERA>().gameOver = true;
         }
     }
+    public static void FengSpecModeToggle()
```
Comment (Lithrun) [inline Assets/Scripts/FengGameManagerMKII.cs]: Move this method to IN_GAME_MAIN_CAMERA. Rename to ToggleSpecmode

File: Assets/Scripts/FengGameManagerMKII.cs [hunk 4]
```diff
@@ -1471,6 +1480,7 @@ private void loadskin()
                 }
             }
             Camera.main.GetComponent<SpectatorMovement>().disable = true;
+            Camera.main.GetComponent<Assets.Scripts.UI.Camera.MouseLook>().disable = true;
```
Comment (Lithrun) [inline Assets/Scripts/FengGameManagerMKII.cs:1386]: Import the namespace, and use MouseLook instead of Assets.Scripts.UI.Camera.MouseLook

File: Assets/Scripts/FengGameManagerMKII.cs [hunk 5]
```diff
@@ -2952,6 +2962,7 @@ public void restartGameSingle2()
         this.ShowHUDInfoCenter(string.Empty);
         this.DestroyAllExistingCloths();
         Application.LoadLevel(Application.loadedLevel);
+
```
Comment (Lithrun) [inline Assets/Scripts/FengGameManagerMKII.cs]: Remove this

File: Assets/Scripts/FengGameManagerMKII.cs [hunk 6]
```diff
@@ -3464,8 +3475,7 @@ public void SpawnPlayerAt2(string id, GameObject pos)
             component.enabled = true;
             GameObject.Find("MainCamera").GetComponent<IN_GAME_MAIN_CAMERA>().setHUDposition();
             GameObject.Find("MainCamera").GetComponent<SpectatorMovement>().disable = true;
-            //TODO MouseLook
-            //GameObject.Find("MainCamera").GetComponent<MouseLook>().disable = true;
+            GameObject.Find("MainCamera").GetComponent<Assets.Scripts.UI.Camera.MouseLook>().disable = true;
```
Comment (Lithrun) [inline Assets/Scripts/FengGameManagerMKII.cs]: Import the namespace, and use MouseLook instead of Assets.Scripts.UI.Camera.MouseLook

File: Assets/Scripts/FengGameManagerMKII.cs [hunk 7]
```diff
@@ -3546,8 +3556,7 @@ public void spawnPlayerAtRPC(float posX, float posY, float posZ, PhotonMessageIn
...
```
Comment (Lithrun) [inline Assets/Scripts/FengGameManagerMKII.cs]: Import the namespace, and use MouseLook instead of Assets.Scripts.UI.Camera.MouseLook

File: Assets/Scripts/FengGameManagerMKII.cs [hunk 8]
```diff
@@ -3630,8 +3639,7 @@ public void SpawnPlayerTitan()
         GameObject.Find("MainCamera").GetComponent<IN_GAME_MAIN_CAMERA>().setMainObjectASTITAN(playerTitan.gameObject);
         GameObject.Find("MainCamera").GetComponent<IN_GAME_MAIN_CAMERA>().enabled = true;
         GameObject.Find("MainCamera").GetComponent<SpectatorMovement>().disable = true;
-        //TODO MouseLook
-        //GameObject.Find("MainCamera").GetComponent<MouseLook>().disable = true;
+        GameObject.Find("MainCamera").GetComponent<Assets.Scripts.UI.Camera.MouseLook>().disable = true;
```
Comment (Lithrun) [inline Assets/Scripts/FengGameManagerMKII.cs]: Import the namespace, and use MouseLook instead of Assets.Scripts.UI.Camera.MouseLook

File: Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs [hunk 9]
```diff
@@ -244,11 +246,8 @@ public void setSpectorMode(bool val)
     {
         this.spectatorMode = val;
         GameObject.Find("MainCamera").GetComponent<SpectatorMovement>().disable = !val;
-
-        //TODO MouseLook
-        //GameObject.Find("MainCamera").GetComponent<MouseLook>().disable = !val;
+        GameObject.Find("MainCamera").GetComponent<Assets.Scripts.UI.Camera.MouseLook>().disable = !val;
```
Comment (Lithrun) [inline Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs]: Import the namespace, and use MouseLook instead of Assets.Scripts.UI.Camera.MouseLook

File: Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs [hunk 10]
```diff
@@ -427,57 +426,63 @@ public void update2()
...
-                    }
-                    else
-                    {
-                        this.setSpectorMode(true);
-                    }
-                }
-                if (InputManager.KeyDown(InputHuman.Item1))
+                
+                this.setSpectorMode(true);
+                FengGameManagerMKII.instance.ShowHUDInfoCenter(
```
Comment (Lithrun) [inline Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs:440]: FengGameManagerMKII.instance.ShowHUDInfoCenter( can be removed here, as it does nothing.

**Review by Lithrun — CHANGES_REQUESTED** [review]
10 small maintainability improvements

File: Assets/Scripts/FengGameManagerMKII.cs (hunk 5 above)
Comment (FAStre) [reply Assets/Scripts/FengGameManagerMKII.cs]: The whitespace?

File: Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs (hunk 10 above)
Comment (FAStre) [reply Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs:440]: I tested and this is the one displaying HUD, the duplicate in FengGameManagerMKII doesn't for some reason, and i did remove it there to test as well.

File: Assets/Scripts/FengGameManagerMKII.cs (hunk 5 above)
Comment (Lithrun) [reply Assets/Scripts/FengGameManagerMKII.cs]: You added a random new line there, why? We don't need that, so remove it

File: Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs (hunk 10 above)
Comment (Lithrun) [reply Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs:440]: On which gamemode did you test it? The second ShowHUDInfo center only gets called when your gamemode is NOT Racing

Comment (FAStre) [reply Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs:440]: I tested all gamemodes. Removing the HUD statements from FengGameManagerMKII and keeping it here keeps it open, idk why but it does

**Review by FAStre — COMMENTED** [review]
Resolved

**Review by Lithrun — APPROVED** [review]
