### PR TITLE
Fixed player titan sliding around on death

### LINKED ISSUE #389: [BUG] Player titans moving on death
**Describe the bug**
If you suicide while moving as a player titan your model slides across the floor of the map until it despawns.

**To Reproduce**
1. Create a multiplayer lobby on forest
2. Spawn as a titan
3. Hold W
4. Suicide while still holding W

**Expected behavior**
Your model should fall and remain motionless after suiciding.

**Additional context**
I'm guessing this is because your speed isn't reset to 0 after suiciding, so your model continues to slide at the speed you were moving before suiciding.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

### PR DESCRIPTION
**Pull request by mash8**
Closes #389

### CODE REVIEW

File: Assets/Scripts/Characters/Titan/MindlessTitan.cs [hunk 1]
```diff
@@ -521,6 +521,7 @@ private void Explode()
         private bool HasDieSteam { get; set; }
         protected void Dead()
         {
+            Rigidbody.velocity = new Vector3(0, Rigidbody.velocity.y, 0);
```
Comment (Lithrun) [inline Assets/Scripts/Characters/Titan/MindlessTitan.cs]: Don't think we need this line of code, as that will instantly kill any existing speed which a titan has. The check to see if the titan is alive in PlayerTitan should be sufficient

**Review by Lithrun — CHANGES_REQUESTED** [review]

File: Assets/Scripts/Characters/Titan/MindlessTitan.cs (hunk 1 above)
Comment (mash8) [reply Assets/Scripts/Characters/Titan/MindlessTitan.cs]: This is actually necessary for the fix to work. Without it the player titan will still slide around.

Comment (Lithrun) [reply Assets/Scripts/Characters/Titan/MindlessTitan.cs]: See https://github.com/AoTTG-2/AoTTG-2/pull/427/commits/2f5fddc323807e5d37321241ce5e851964f0638a for a solution where PTs will no longer move, and without affecting the previous logic
