### PR TITLE
#179 unresponsive reel in scroll wheel

### LINKED ISSUE #179: [BUG] Reel-in feels unresponsive, especially with default controls
**Describe the bug**
Reeling in feels unresponsive to many testers, including some who are used to playing with default controls.  The responsiveness seems to go up when performing critical reel ins (reeling in the moment a hook lands), and goes down when orbiting around an object; this may be related to issue #97 .

Rebinded reel in using AutoHotKey (which causes another key to send many WheelDown events, as if the player were scrolling the mousewheel extremely fast) *seems* to be more reliable than normal mousewheel scrolling, but some still report unresponsiveness.  Since rebinds *aren't actually implemented*, it's impossible to determine whether the rebinded unresponsiveness is due to AHK or AoTTG 2.

**To Reproduce**
The bug has no true reproduction method; testers *feel* like it's wrong, but it's not nonfunctional, just unreliable.  So, play forest and reel between trees.  Pay attention to the timing of successful reels.  It often feels late.

**Additional comments**
Confirmed on Issue98

May be related to the old AoTTG bug where higher FPS causes reeling to be less responsive because it has to happen on one of the frames where the game actually checks input.  We cannot easily compare how the game performs at different FPS rates due to Issue #178
May be related to Issue #97, since critical reels work better.
*Please* implement rebinds.  The current situation is just terrible.

### PR DESCRIPTION
**Pull request by PhantomRyser**
Ensured that reeling inputs are checked in both the Update and FixedUpdate methods. Will most likely change how inputs are read once Hero.cs is refactored properly but this ensures that there isn't any missed inputs and labelled some variables that were ambiguous.

Closes #179

**Notes for the reviewer:**

*(Add information which you think is important for the reviewer to be aware of (i.e. functionality X is not included as this was too complex, see issue 123))*

**Contributor guidelines:**
1. A build has been uploaded to the discord #builds channel & has been tested by the testing team
2. Assure the code is inline with the [AoTTG2 coding conventions](https://github.com/AoTTG-2/AoTTG-2/wiki/Code-&-Style-Conventions)
3. Fix any issues that the CI reports (Sonarcloud & unit tests)

After all above conditions are met, @Lithrun will review your Pull Request. Resolve any comments of the reviewer or discuss them if you disagree.

### CODE REVIEW

File: Assets/Scripts/Characters/Humans/Hero.cs [hunk 1]
```diff
@@ -1281,6 +1286,37 @@ public void Update()
...
+                reelForce = -1f;
+            }
+            else if (InputManager.Key(InputHuman.ReelOut))
+            {
+                reelForce = 1f;
+            }
+            else if (InputManager.KeyUp(InputHuman.ReelIn) || InputManager.KeyUp(InputHuman.ReelOut))
+            {
+                reelForce = 0f;
+            }
```
Comment (PeteAniDev) [inline Assets/Scripts/Characters/Humans/Hero.cs]: I believe you should use `&&` here instead of `||`.
And remove `else` because if one of the two cases up there is true, those lines will never be reached.

Comment (PhantomRyser) [reply Assets/Scripts/Characters/Humans/Hero.cs]: I don't think that anyone would release the reel in and reel out key binds at the same time which would be what is required to make that if statement true (unless KeyUp always returns true if not pressing the key). I'm not sure but I think it is only true once on the frame that the key is released (or not pressed anymore). 

I realize now that I can get rid of that entire elseif statement because the reelForce will "zero" out at the end of the statement chain if scroll inputs aren't being used.

**Review by Lithrun — APPROVED** [review]
