### PR TITLE
Fixed Duplication Exploit

### LINKED ISSUE #276: [BUG]#276 Duplication exploit
**Describe the bug**
When a player dies, If you click Item1 to spawn, then after spawning use the /specmode command and then spawn again, a duplicate of your character appears.

**To Reproduce**
1. Open any gamemode with titans
2. Die by titan
3. Click Item1 key(1 by default) and spawn
4. Use the /specmode command in chat and spawn using item1 or 1 key again
5. You now have a duplicate player

**Expected behavior**
No duplication should be occurring at all

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

### PR DESCRIPTION
**Pull request by PeteAniDev**
Fixed duplication exploit due to incorrect spectator mode state.

Closes #276

**Contributor guidelines:**
1. A build has been uploaded to the discord #builds channel & has been tested by the testing team
2. Assure the code is inline with the [AoTTG2 coding conventions](https://github.com/AoTTG-2/AoTTG-2/wiki/Code-&-Style-Conventions)
3. Fix any issues that the CI reports (Sonarcloud & unit tests)

After all above conditions are met, @Lithrun will review your Pull Request. Resolve any comments of the reviewer or discuss them if you disagree.

### CODE REVIEW

**Comment by PeteAniDev** [comment]
Since the issue is resolved, I will not continue working on migrating Fenglee Codes to the new system as this "Code Smell" part is related to Gamemode settings. The migration of this should be completed once needChooseSide instance of Fenglee is migrated.

**Comment by Lithrun** [comment]
> 
> 
> Since the issue is resolved, I will not continue working on migrating Fenglee Codes to the new system as this "Code Smell" part is related to Gamemode settings. The migration of this should be completed once needChooseSide instance of Fenglee is migrated.

That's fine, as Gamemode Settings are significantly changed as per #604 (You can take a peek at #694)

Sonarcloud comments are there as a warning, not as an error. So you can ignore those which aren't relevant to your issue. If there is one which shouldn't be ignored, then you will hear it from me

File: Assets/Scripts/FengGameManagerMKII.cs [hunk 1]
```diff
@@ -1543,7 +1507,8 @@ private void loadconfig()
             objArray[0xf2] = PlayerPrefs.GetString("hjump", "Q");
             objArray[0xf3] = PlayerPrefs.GetString("hmount", "LeftControl");
             objArray[0xf4] = PlayerPrefs.GetInt("chatfeed", 0);
-            objArray[0xf5] = 0;
+            objArray[0xf5] = null; // Is no longer in the code
```
Comment (Lithrun) [inline Assets/Scripts/FengGameManagerMKII.cs]: If this is no longer required, then delete it

File: Assets/Scripts/UI/Camera/SpectatorMode.cs [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+using UnityEngine;
+using static Assets.Scripts.FengGameManagerMKII;
+
+namespace Assets.Scripts.Utility
+{
+
+    public static class SpectatorMode
+    {
+
+        private static bool _disable = true;
```
Comment (Lithrun) [inline Assets/Scripts/UI/Camera/SpectatorMode.cs]: Rather switch this "disabled" to "enabled", as it's more common to check if something is enabled or not enabled vs disabled or not disabled.

File: Assets/Scripts/UI/Camera/SpectatorMovement.cs [hunk 3]
```diff
@@ -1,11 +1,13 @@
...
+using Assets.Scripts.Utility;
 using UnityEngine;
 
+// Call with GameObject.Find("MainCamera").GetComponent<SpectatorMovement>()
 public class SpectatorMovement : MonoBehaviour
 {
-    public bool disable;
-    private float speed = 100f;
+    public bool disable = true;
+    private readonly float baseSpeed = 100f;
```
Comment (Lithrun) [inline Assets/Scripts/UI/Camera/SpectatorMovement.cs]: A constant (const) would be better here, as this value will not change throughout the usage of the program. With readonly it is technically allowed to modify the value via the constructor, whereas via const you make this more explicitly clear

File: Assets/Scripts/UI/Camera/SpectatorMovement.cs [hunk 4]
```diff
@@ -16,11 +18,12 @@ private void Awake()
 
     private void Update()
     {
-        if (!this.disable)
+        SpectatorMode.Initialize();
```
Comment (Lithrun) [inline Assets/Scripts/UI/Camera/SpectatorMovement.cs]: Continuously calling an "Initialize" method doesn't seem right to do every frame. This will keep setting the "_disable" to true.

File: Assets/Scripts/UI/Camera/SpectatorMovement.cs [hunk 5]
```diff
@@ -16,11 +18,12 @@ private void Awake()
...
+        if (!disable)
```
Comment (Lithrun) [inline Assets/Scripts/UI/Camera/SpectatorMovement.cs]: You could invert this if statement to make the code a bit more readable. Thus the logic wouldn't be nested within the if statement

Compare:
```
if (disable) return;

// All of the movement logic
```

vs

```
if (!disable)
{
     // All of the movement logic
}
```

**Review by Lithrun — CHANGES_REQUESTED** [review]
See comments. Additionally, what is the exact correlation between the "disabled" state of the SpectatorMode and the actual usage of the EnterSpecMode? Perhaps a cleaner approach would be to call EnterSpecMode whenever the Specmode is enabled / disabled, as then spectator mode specific logic can be within the spectatormode class and the only thing that other classes have to do is to then either enable / disable it

File: Assets/Scripts/UI/Camera/SpectatorMovement.cs (hunk 4 above)
Comment (PeteAniDev) [reply Assets/Scripts/UI/Camera/SpectatorMovement.cs]: Oh, I forgot that thing. It should be in Awake()

**Comment by PeteAniDev** [comment]
The EnterSpecMode() can only be used once everything is initialized. For example, when you press 1 to enter the game you switch out of spectator mode. But your body is not initialized yet so the EnterSpecMode() should run after you spawn your hero.
My Unity crashed when trying to put EnterSpecMode() in Toggle(), Disable(), and Enable().

I'll change its name from EnterSpecMode() to UpdateSpecMode() for clarity.

**Review by Lithrun — APPROVED** [review]
