### PR TITLE
#752 Invisible Blade Bug

### LINKED ISSUE #752: Interrupting the reloading animation can result in an invisible blade. [BUG]
**Describe the bug**
The title described its all.

**To Reproduce**
1. Spawn as a hero.
2. Reload.
3. Hook to interrupt the reload.
4. Kill titans with the invisible blade.

**Expected behavior**
Interrupting reload animation should make the hero fail to reload and have to reload again.
The HUD should also display that you haven't reloaded yet.

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

### PR DESCRIPTION
**Pull request by Zynku**
Closes #752

**Notes for the reviewer:**

Should work as intended. Interrupting a reload animation with blades will now give the player the new blade anyway, and act like the animation wasn't interrupted. If you think the player should not be given the new blade, and should be instead forced to reload again, please state so.

**Contributor guidelines:**
1. A build has been uploaded to the discord #builds channel & has been tested by the testing team
2. Assure the code is inline with the [AoTTG2 coding conventions](https://github.com/AoTTG-2/AoTTG-2/wiki/Code-&-Style-Conventions)
3. Fix any issues that the CI reports (Sonarcloud & unit tests)

After all above conditions are met, @Lithrun will review your Pull Request. Resolve any comments of the reviewer or discuss them if you disagree.

### CODE REVIEW

File: Assets/Scripts/Characters/Humans/Hero.cs [hunk 1]
```diff
@@ -449,6 +450,12 @@ public void Update()
                 bool isLeftHookPressed;
                 BufferUpdate();
                 UpdateExt();
+                if (state != HumanState.ChangeBlade && weaponDisabledOnReloading)
+                {
+                    //If the reload animation is cancelled before the weapon has a chance to be reenabled, call this function to do that
+                    Equipment.Weapon.EnableWeapons();
+                }
```
Comment (PeteAniDev) [inline Assets/Scripts/Characters/Humans/Hero.cs:463]: The weapon will be enabled repeatedly since Equipment.Weapon.EnableWeapons() does not change weaponDisabledOnReloading to false. Indeed, I don't see that weaponDisabledOnReloading is ever false. See the next review, it might be a possible solution.

File: Assets/Scripts/Characters/Humans/Equipment/Weapon/Blades.cs [hunk 2]
```diff
@@ -26,40 +27,54 @@ public override void PlayReloadAnimation()
...
+        {
+            if (TotalBlades > 0)
+            {
+                WeaponLeft.SetActive(true);
+                WeaponRight.SetActive(true);
+                Hero.currentBladeSta = Hero.totalBladeSta;
+                bladesThrown = false;
+                Hero.weaponDisabledOnReloading = true;
+            }
+        }
```
Comment (PeteAniDev) [inline Assets/Scripts/Characters/Humans/Equipment/Weapon/Blades.cs]: Since this enables the weapons, shouldn't this set Hero.weaponDisabledOnReloading to false instead of true?

**Review by PeteAniDev — CHANGES_REQUESTED** [review]
Canceling the reload helps you instantly reload is a cool mechanic, but you should wait for Lithrun to approve this idea.

File: Assets/Scripts/Characters/Humans/Equipment/Weapon/Blades.cs (hunk 2 above)
Comment (Zynku) [reply Assets/Scripts/Characters/Humans/Equipment/Weapon/Blades.cs]: Yeah, I suppose I have the name backwards, should probably be called weaponEnabledAfterReloading, or invert the bool's usage

Comment (PeteAniDev) [reply Assets/Scripts/Characters/Humans/Equipment/Weapon/Blades.cs]: Well even if you change the name, the boolean is still always true, so it might be unnecessary.

File: Assets/Scripts/Characters/Humans/Hero.cs (hunk 1 above)
Comment (Zynku) [reply Assets/Scripts/Characters/Humans/Hero.cs:463]: This function is called only when its any state but reloading. I.e. if we switch to a hook animation, and the weapons are still disabled, then it will be called, which does the "reloading" instantly. It's set to false in the function that throws the blades so that its true in the frames between the blades being thrown (since they disappear then) and the blades being brought of the holsters (they are reenabled here)

Comment (Zynku) [reply Assets/Scripts/Characters/Humans/Hero.cs:463]: Wait...

**Review by Lithrun — APPROVED** [review]
