### PR TITLE
#725 trail not disappearing

### LINKED ISSUE #725: [BUG]Weapon trail not disappearing
**Describe the bug**
If you hook a wall or gas burst when the trail is visible, it won't disappear until a normal or special attack is performed.
**NOTE: The build in which this issue/bug is present has currently not merged with any of the major alpha builds**

**To Reproduce**
1. Get on any map and hook a wall or gas burst when the trail is visible i.e hook a wall while in attack animation

**Expected behavior**
The trail should disappear after the attack animation is cancelled due to hooking an object or doing a gas burst and should not be visible 

**Screenshots**
image

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

### LINKED ISSUE #732: [BUG] FPS Counter Inaccuracy
**Describe the bug**
The FPS counter does not update update as often as it should, and the number it displays is sometimes higher or lower than what your FPS actually is. The more FPS you have, the further above or below the counter may be.

**To Reproduce**
1. Use some form of external FPS tracker and launch AoTTG2
2. Compare your actual FPS to what the FPS tracker in-game displays

**Expected behavior**
The FPS tracker should update more often (perhaps every 1-2 seconds) and should be accurate to what your actual FPS is.

**Video**
The green number at the top left is my actual FPS. The smaller green number at the bottom left is the in-game FPS tracker.
https://youtu.be/y-5mNt3FqGs

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

### PR DESCRIPTION
**Pull request by Mi-Sad**
Closes #725

**Notes for the reviewer:**

also added some utility extention function that may come handy to trim down in redundancy while managing hero custom prop (put in RCExtension SafeGet<>)

**Contributor guidelines:**
1. A build has been uploaded to the discord #builds channel & has been tested by the testing team
2. Assure the code is inline with the [AoTTG2 coding conventions](https://github.com/AoTTG-2/AoTTG-2/wiki/Code-&-Style-Conventions)
3. Fix any issues that the CI reports (Sonarcloud & unit tests)

After all above conditions are met, @Lithrun will review your Pull Request. Resolve any comments of the reviewer or discuss them if you disagree.

### CODE REVIEW

File: Assets/Photon Unity Networking/Resources/PhotonServerSettings.asset [hunk 1]
```diff
@@ -15,14 +15,14 @@ MonoBehaviour:
   AppID: 
   VoiceAppID: 
   ChatAppID: 
-  HostType: 2
```
Comment (Lithrun) [inline Assets/Photon Unity Networking/Resources/PhotonServerSettings.asset]: Same as the other PR (don't include these changes)

File: Assets/Scripts/Legacy/RCextensions.cs [hunk 2]
```diff
@@ -171,6 +172,27 @@ public static float returnFloatFromObject(object obj)
         return 0f;
     }
 
+    public static T SafeGet<T, T1, T2>(this IDictionary<T1, T2> h, T1 key) where T : new()
```
Comment (Lithrun) [inline Assets/Scripts/Legacy/RCextensions.cs]: These extension methods seem fine, but:
1. Move it to a dedicated extensions class, as RCExtensions is declared obsolete so no new logic should be added here
2. For extension methods, please also include /// summary comments

**Review by Lithrun — CHANGES_REQUESTED** [review]
