### PR TITLE
Vsync and general graphics settings

### LINKED ISSUE #733: [BUG] V-Sync Forced on by Default
**Describe the bug**
By default, upon launching a build for the first time, v-sync is forced on. You can disable it by setting 0 in the FPS Limiter, but it should be disabled by default and toggled to turn on in Graphic Settings.

**To Reproduce**
1. Setup some form of external FPS tracker as the in-game one is inaccurate.
2. Launch AoTTG2, and note that your FPS is locked to your monitor's refresh rate
3. Create a lobby, and open the menu with escape
4. Go to Graphic Settings, and type 0 in the FPS Limiter and save
5. Restart and wait a second (or go back to the main menu), and you should see your FPS is now uncapped

**Expected behavior**
V-Sync should only be on when toggled on.

**Additional context**
This is important to fix, or at the very least make everyone aware of, as this alongside the inaccuracy of the FPS counter is distorting people's views on the game's performance.

Note: the reason V-Sync was forced originally was because the main menu has no inherent FPS cap, meaning it can pull far too much system resources if left sitting. A unique FPS cap should be set for the main menu, and the rest of the game should remain uncapped by default.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

### PR DESCRIPTION
**Pull request by Zoap**
sets framerate to monitor refreshrate when entering the menu

Closes #733 

**Notes for the reviewer:**
GeneralGraphics.cs and GraphicsController.cs have been refactored.
Moved/extended the functionality of the old class FPSLimiter to a new helper class.
Because of how quality settings work in unity I decided to not make that which we cannot change be interactable (shadows, AA etc) and to leave the quality slider interactable at all times.
I commented out a lot of code that has to do with changing quality, the reason is that some quality parameters can not be decoupled from the SetQualityLevel value see [link](https://forum.unity.com/threads/change-shadow-resolution-from-script.784793/page-2)

**Contributor guidelines:**
1. A build has been uploaded to the discord #builds channel & has been tested by the testing team
2. Assure the code is inline with the [AoTTG2 coding conventions](https://github.com/AoTTG-2/AoTTG-2/wiki/Code-&-Style-Conventions)
3. Fix any issues that the CI reports (Sonarcloud & unit tests)

After all above conditions are met, @Lithrun will review your Pull Request. Resolve any comments of the reviewer or discuss them if you disagree.

### CODE REVIEW

**Comment by Zoap** [comment]
pending test

**Comment by Zoap** [comment]
Testing done, go for merge.

File: Assets/Scripts/UI/InGame/Graphics/GeneralGraphics.cs [hunk 1]
```diff
@@ -1,23 +1,33 @@
...
+        {
+            get { return fpsLimit; }
+            set { fpsLimit = value; }
+        }
 
+        public QualitySwitcher QualitySwitcher
+        {
+            get { return qualitySwitcher; }
+            set { qualitySwitcher = value; }
+        }
```
Comment (Lithrun) [inline Assets/Scripts/UI/InGame/Graphics/GeneralGraphics.cs]: Rather make the fpsLimit & qualitySwitcher fields public, as the getter & setter aren't doing anything special here

File: Assets/AoTTG 2.unity [hunk 2]
```diff
@@ -115,7 +115,7 @@ Transform:
   m_LocalScale: {x: 0.0027777802, y: 0.002777778, z: 0.00277778}
   m_Children: []
   m_Father: {fileID: 0}
-  m_RootOrder: 3
```
Comment (Lithrun) [inline Assets/AoTTG 2.unity]: Did you change anything to the main scene? If so, rather undo all changes here as it seems like Unity is doing something weird here:
image

File: Assets/Scripts/Graphics/FramerateController.cs [hunk 3]
```diff
@@ -0,0 +1,23 @@
+using UnityEngine;
+
+namespace Assets.Scripts.Graphics
+{
+    public static class FramerateController
```
Comment (Lithrun) [inline Assets/Scripts/Graphics/FramerateController.cs:8]: For static classes, please add /// summary documentation

File: Assets/Scripts/UI/InGame/Graphics/GeneralGraphics.cs (hunk 1 above)
Comment (Lithrun) [reply Assets/Scripts/UI/InGame/Graphics/GeneralGraphics.cs]: Although, looking at the other fields, it's also done there for some reason? So if you can, please also remove the useless properties from line 32 - 67 (TextureQuality till CustomSettings)

File: Assets/Scripts/UI/InGame/Graphics/GeneralGraphics.cs [hunk 4]
```diff
@@ -56,126 +66,126 @@ public Toggle CustomSettings
             set { customSettings = value; }
         }
 
-        public void UpdateObjects()
+        protected void Start()
```
Comment (Lithrun) [inline Assets/Scripts/UI/InGame/Graphics/GeneralGraphics.cs]: Can make this one private

File: Assets/Scripts/UI/InGame/Graphics/GeneralGraphics.cs [hunk 5]
```diff
@@ -56,126 +66,126 @@ public Toggle CustomSettings
...
-            //             VSyncCheck.text = "VSync is on!!";
-            //         }
-            //else
-            //{
-            //	QualitySettings.vSyncCount = 0;
-            //             VSyncCheck.text = "";
-            //         }
+            var parsed = int.TryParse(limit, out int frameRate);
+
+            if (parsed)
```
Comment (Lithrun) [inline Assets/Scripts/UI/InGame/Graphics/GeneralGraphics.cs]: Instead of this, you can also do:
```csharp
if(int.TryParse(limit, out var frameRate))
```

File: Assets/Scripts/UI/InGame/Graphics/QualitySwitcher.cs [hunk 6]
```diff
@@ -8,12 +8,21 @@ public class QualitySwitcher : UiElement {
 		public Text Label;
 		public Slider Slider;
 
-		public void UpdateQuality()
+        private void Start()
```
Comment (Lithrun) [inline Assets/Scripts/UI/InGame/Graphics/QualitySwitcher.cs:11]: The indentation of this class seems messed up somehow. So please format the document (Visual Studio: Ctrl+K, D )

File: Assets/Scripts/UI/InGame/Graphics/GraphicsController.cs [hunk 7]
```diff
@@ -1,173 +1,125 @@
-﻿using UnityEngine;
+﻿using System;
+using UnityEngine;
 using UnityEngine.UI;
-using System;
 
 namespace Assets.Scripts.UI.InGame
 {
-	public class GraphicsController : MonoBehaviour {
+    public class GraphicsController : MonoBehaviour {
```
Comment (Lithrun) [inline Assets/Scripts/UI/InGame/Graphics/GraphicsController.cs]: Indentation is also messed up here. So same as other comment:
`The indentation of this class seems messed up somehow. So please format the document (Visual Studio: Ctrl+K, D )`

File: Assets/Scripts/UI/InGame/Graphics/GraphicsController.cs [hunk 8]
```diff
@@ -1,173 +1,125 @@
...
-		// Index of the custom quality level
-		public const int CUSTOM = 6;
-		public const string GDATA = "GraphicsData";
+        public const string GDATA = "GraphicsData";
 		public const string QDATA = "QualityProfile";
-		public const string FDATA = "FPSLimit";
+        public const string FDATA = "FPSLimit";
 
-		private void Start()
+        protected void Start()
```
Comment (Lithrun) [inline Assets/Scripts/UI/InGame/Graphics/GraphicsController.cs]: Why was this changed to protected?

**Review by Lithrun — CHANGES_REQUESTED** [review]

File: Assets/AoTTG 2.unity (hunk 2 above)
Comment (Zoap) [reply Assets/AoTTG 2.unity]: re import all assets, it's not the brach, since I re imported all the assests before pushing

File: Assets/Scripts/UI/InGame/Graphics/GeneralGraphics.cs (hunk 1 above)
Comment (Zoap) [reply Assets/Scripts/UI/InGame/Graphics/GeneralGraphics.cs]: i'll get on that, i'm a bit rusty so I just did it the way it had been done previously

File: Assets/Scripts/UI/InGame/Graphics/QualitySwitcher.cs (hunk 6 above)
Comment (Zoap) [reply Assets/Scripts/UI/InGame/Graphics/QualitySwitcher.cs:11]: it looked fine on my end

File: Assets/Scripts/UI/InGame/Graphics/GraphicsController.cs (hunk 8 above)
Comment (Zoap) [reply Assets/Scripts/UI/InGame/Graphics/GraphicsController.cs]: because visual studio was having an attitude about it being private since it hides the inherited method, and I am obviously a slave to VS whims and wishes :)

File: Assets/Scripts/UI/InGame/Graphics/GraphicsController.cs (hunk 7 above)
Comment (Zoap) [reply Assets/Scripts/UI/InGame/Graphics/GraphicsController.cs]: looked fine on my end, still formatted tho

File: Assets/AoTTG 2.unity (hunk 2 above)
Comment (Zoap) [reply Assets/AoTTG 2.unity]: maybe not, i'm getting it as well

Comment (Zoap) [reply Assets/AoTTG 2.unity]: I believe I fixed it

**Review by Lithrun — APPROVED** [review]
LithrunsSealOfApproval
